on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: ./.github/actions/setup-node
      - run: pnpm run format
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: format [skip ci]"
